name: Get and cache dependencies
description: A reusable workflow to get and cache dependencies.
inputs:
  cache-key:
    description: The key to use for caching dependencies.
    required: false
    default: 'true'
outputs:
  updated-cache:
    description: Whether the cache was hit or not.
    value: ${{ steps.install-deps.outputs.updated-cache }}
runs:
  using: composite
  steps:
    - name: Cache dependencies
      if: inputs.cache-key == 'true'
      id: cache
      uses: actions/cache@v5
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install-deps
      if: steps.cache.outputs.cache-hit != 'true' || inputs.cache-key != 'true'
      run: |
        npm ci
        echo "updated-cache=true" >> $GITHUB_OUTPUT
      shell: bash