name: Deployment
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Load and cache dependencies
        id: cache-deps
        uses: ./.github/actions/cache-deps
        with:
          cache-key: 'false'
      - name: Output contents
        id: output-cache
        run: |
          echo "Cache hit: ${{ steps.cache-deps.outputs.updated-cache }}"
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Load and cache dependencies
        uses: ./.github/actions/cache-deps
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v7
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Load and cache dependencies
        uses: ./.github/actions/cache-deps
      - name: Build website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist-files
          path: dist
  deploy:
    permissions:
      id-token: write
      contents: read
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Get build artifacts
        uses: actions/download-artifact@v7
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
      - name: Get AWS permissions
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::122795416834:role/GHAction-demo
          aws-region: eu-west-2
      - name: Deploy site
        id: deploy-s3
        uses: ./.github/actions/deploy-s3-docker
        with:
          bucket-name: gha-security-demo-122795416834-eu-west-2-an
          dist-path: ./dist
      - name: Output website URL
        run: |
          echo "Website URL: ${{ steps.deploy-s3.outputs.website-url }}"